# Generated by Django 5.0.6 on 2024-11-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquote',
            managers=[
            ],
        ),
    ]
