# Generated by Django 5.0.6 on 2024-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stockquote_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquote',
            name='raw_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
