# Generated by Django 5.0.6 on 2024-11-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_stockquote_raw_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquote',
            unique_together={('company', 'time')},
        ),
    ]
